set_active_sensor:
  name: Set active sensor
  description: Changes the active temperature sensor for your Nest thermostat.
  fields:
    entity_id:
      name: Nest Thermostat
      description: The Nest thermostat to operate on.
      example: climate.nest
      required: true
      selector:
        entity:
          domain: climate
          integration: badnest
    sensor:
      name: Nest Sensor
      description: The Nest temperature sensor to use as the active sensor.
      example: sensor.bedroom_nest_sensor
      required: true
      selector:
        entity:
          domain: sensor
          integration: badnest
