name: Release

on:
  release:
    types:
    - prereleased
    - released


jobs:
  upload_release:
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v3
      - name: Zip up release
        run: |
          zip badnest.zip -r ./
        working-directory: custom_components/badnest
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/badnest/badnest.zip
          asset_name: badnest.zip
          tag: ${{ github.ref }}
          overwrite: true
