name: Validate

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
  - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
    - name: Code checkout
      uses: "actions/checkout@v2"
    - name: Hassfest validation
      uses: "home-assistant/actions/hassfest@master"
    - name: HACS validation
      uses: "hacs/action@21.12.0"
      with:
        category: "integration"
        ignore: "brands"
